# Generated by Django 3.1.2 on 2020-11-09 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Memory',
        ),
    ]
