# Generated by Django 3.1.2 on 2021-01-30 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myInsta', '0002_auto_20210130_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
