# Generated by Django 3.1.2 on 2021-01-30 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myInsta', '0003_auto_20210130_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.TextField(null=True),
        ),
    ]
