# Generated by Django 3.1.2 on 2021-02-01 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myInsta', '0006_auto_20210201_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.TextField(null=True),
        ),
    ]
