# Generated by Django 3.1.2 on 2021-02-01 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myInsta', '0007_auto_20210201_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_bio',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
