# Generated by Django 3.1.2 on 2021-02-01 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myInsta', '0009_auto_20210201_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default='12:44:16', verbose_name='Date'),
        ),
    ]
