# Generated by Django 3.1.2 on 2021-02-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myInsta', '0013_auto_20210201_1248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-DateandTime']},
        ),
        migrations.RemoveField(
            model_name='post',
            name='time',
        ),
        migrations.AddField(
            model_name='post',
            name='DateandTime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='DateTime'),
        ),
    ]
