# Generated by Django 3.0.3 on 2021-02-03 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myInsta', '0016_auto_20210202_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='curr_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myInsta.Profile'),
        ),
    ]
