# Generated by Django 3.0.3 on 2021-02-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myInsta', '0019_auto_20210204_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
    ]
