# Generated by Django 3.0.3 on 2021-02-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myInsta', '0020_likes_likes_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='likes_count',
        ),
        migrations.AddField(
            model_name='post',
            name='post_likes',
            field=models.IntegerField(default=0),
        ),
    ]
