# Generated by Django 3.1.2 on 2021-02-11 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myInsta', '0022_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='curr_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='myInsta.post'),
        ),
    ]
